import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { IoClose, IoChatbubbleEllipses } from 'react-icons/io5';

// Simple "Pop" Sound - Base64 WAV
const notificationSound = 'data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YU...'; // Placeholder

// Actually, let's use a real short beep (sine wave) generated by AudioContext to be self-sufficient and guaranteed to work without external files!
const playNotificationSound = () => {
  try {
    const AudioContext = window.AudioContext || window.webkitAudioContext;
    if (!AudioContext) return;

    const ctx = new AudioContext();
    const osc = ctx.createOscillator();
    const gainNode = ctx.createGain();

    osc.connect(gainNode);
    gainNode.connect(ctx.destination);

    osc.type = 'sine';
    osc.frequency.setValueAtTime(500, ctx.currentTime); // 500Hz beep
    osc.frequency.exponentialRampToValueAtTime(1000, ctx.currentTime + 0.1); // Slide up to 1000Hz (chirp)

    gainNode.gain.setValueAtTime(0.1, ctx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.3);

    osc.start();
    osc.stop(ctx.currentTime + 0.3);
  } catch (e) {
    console.warn("Audio Context error", e);
  }
};

const Toast = ({ message, onClose, onClick }) => {
  useEffect(() => {
    // Play Sound on Mount
    playNotificationSound();

    const timer = setTimeout(() => {
      onClose();
    }, 4000); // Auto close after 4s
    return () => clearTimeout(timer);
  }, [onClose]);

  return (
    <motion.div
      initial={{ opacity: 0, y: -50, scale: 0.8, width: 100 }}
      animate={{ opacity: 1, y: 10, scale: 1, width: 360 }}
      exit={{ opacity: 0, y: -50, scale: 0.5, transition: { duration: 0.2 } }}
      transition={{ type: "spring", stiffness: 400, damping: 25 }}
      onClick={onClick}
      className="fixed top-4 left-1/2 -translate-x-1/2 z-[100] h-16 bg-black text-white shadow-2xl rounded-full px-2 cursor-pointer flex items-center gap-3 hover:bg-neutral-900 transition-colors border border-white/10"
    >
      <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500 flex items-center justify-center shrink-0 ml-1">
        <IoChatbubbleEllipses size={20} className="text-white" />
      </div>

      <div className="flex-1 min-w-0 flex flex-col justify-center pr-2">
        <div className="flex justify-between items-center w-full">
          <h4 className="font-bold text-sm truncate text-white">
            {message.group_name ? message.group_name : message.sender}
          </h4>
          <span className="text-[10px] text-gray-400">now</span>
        </div>
        <p className="text-gray-300 text-xs line-clamp-1 break-words opacity-90">
          {message.group_name && <span className="font-semibold text-white mr-1">{message.sender}:</span>}
          {message.content}
        </p>
      </div>

      {/* Optional: No close button on dynamic island usually, but keeping it small if needed or relying on auto-close/swipe up logic. Let's keep a tiny one or remove it for true 'island' feel. Let's keep a minimal one. */}
      {/* <button 
        onClick={(e) => { e.stopPropagation(); onClose(); }}
        className="text-gray-500 hover:text-white p-1 rounded-full hover:bg-white/10 transition-colors shrink-0 mr-1"
      >
        <IoClose size={14} />
      </button> */}
    </motion.div>
  );
};

export default Toast;
