# Generated by Django 5.2.6 on 2025-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_profile_is_private_chatroom_chatmessage_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='editor_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/music/'),
        ),
        migrations.AddField(
            model_name='story',
            name='music_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
