# Generated by Django manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0003_story_editor_json_story_music_file_story_music_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.IntegerField(default=15),
        ),
    ]
