# Generated by Django 5.2.6 on 2025-12-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0005_reel_reelcomment_reellike'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='reel',
            name='editor_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='reels/music/'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
