# Generated by Django 5.2.6 on 2025-12-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0006_reel_duration_reel_editor_json_reel_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
