# Generated by Django manually

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='shared_reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_chats', to='trend.reel'),
        ),
    ]
