# Generated by Django 5.2.6 on 2026-01-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0011_chatmessage_shared_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twist',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='twist',
            name='twist_author',
        ),
        migrations.AddField(
            model_name='notification',
            name='twist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trend.twist'),
        ),
        migrations.AddField(
            model_name='twist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twist',
            name='original_twist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retwists', to='trend.twist'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_reel', 'Like Reel'), ('like_twist', 'Like Twist'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accept'), ('comment_post', 'Comment Post'), ('comment_reel', 'Comment Reel'), ('comment_twist', 'Comment Twist'), ('story_like', 'Story Like')], max_length=20),
        ),
        migrations.AlterField(
            model_name='twist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TwistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('twist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trend.twist')),
            ],
        ),
        migrations.CreateModel(
            name='TwistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='trend.twist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('twist', 'user')},
            },
        ),
    ]
