# Generated by Django 5.2.6 on 2026-01-31 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0012_remove_twist_original_post_remove_twist_twist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twist',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twists', to='trend.post'),
        ),
    ]
