# Generated by Django 5.2.6 on 2026-01-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0013_twist_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='shared_twist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_chats', to='trend.twist'),
        ),
    ]
