# Generated by Django 5.2.6 on 2026-03-18 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0019_saveditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='required_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='required_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twist',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twist',
            name='required_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, help_text='List of features', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('creator', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trend.subscriptionplan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'creator')},
            },
        ),
    ]
