# Generated by Django 5.2.6 on 2026-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0021_creatorearning_creatorpayout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='creator',
        ),
    ]
