# Generated by Django 5.2.6 on 2026-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0022_alter_subscriptionplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='required_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, null=True),
        ),
    ]
