# Generated by Django 5.2.6 on 2026-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0023_story_is_exclusive_story_required_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_creator_terms',
            field=models.BooleanField(default=False),
        ),
    ]
