# Generated by Django 5.2.6 on 2026-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0024_profile_accepted_creator_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accepted_creator_terms',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
