# Generated by Django 5.2.6 on 2026-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0026_profile_withdrawal_info_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reel',
            old_name='video_file',
            new_name='media_file',
        ),
        migrations.AddField(
            model_name='reel',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='video', max_length=10),
        ),
    ]
