# Generated by Django 5.2.6 on 2026-03-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0028_reelview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReelView',
        ),
    ]
