# Generated by Django 5.2.6 on 2026-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0030_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
