# Generated by Django 5.2.6 on 2026-04-04 10:39

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0031_add_gender_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('normal', 'Normal Story'), ('live', 'Live Stream Record')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_reel', 'Like Reel'), ('like_twist', 'Like Twist'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accept'), ('comment_post', 'Comment Post'), ('comment_reel', 'Comment Reel'), ('comment_twist', 'Comment Twist'), ('story_like', 'Story Like'), ('live_start', 'User is Live')], max_length=20),
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='live_previews/')),
                ('viewer_count', models.IntegerField(default=0)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('required_tier', models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=10, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='live_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trend.livestream'),
        ),
        migrations.CreateModel(
            name='LiveStreamViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='trend.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stream', 'user')},
            },
        ),
    ]
