# Generated by Django 5.2.6 on 2026-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0032_story_story_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='live_stream',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_reel', 'Like Reel'), ('like_twist', 'Like Twist'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accept'), ('comment_post', 'Comment Post'), ('comment_reel', 'Comment Reel'), ('comment_twist', 'Comment Twist'), ('story_like', 'Story Like')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LiveStreamViewer',
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
