# Generated by Django 5.2.6 on 2026-04-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0033_remove_notification_live_stream_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Like Post'), ('like_reel', 'Like Reel'), ('like_twist', 'Like Twist'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accept'), ('comment_post', 'Comment Post'), ('comment_reel', 'Comment Reel'), ('comment_twist', 'Comment Twist'), ('story_like', 'Story Like'), ('req_approved', 'Request Approved'), ('req_rejected', 'Request Rejected')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
